import Container from "@/app/components/Container";
import Navbar from "@/app/components/Navbar";
import { GlobalProvider } from "@/app/context/GlobalContext";
import "@/app/globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <GlobalProvider>
          <Navbar />
          <Container>{children}</Container>
        </GlobalProvider>
      </body>
    </html>
  );
}
